### ISSUE TITLE
apply not idempotent

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#234]
Our implementation of `bootc update --apply` has an obvious bug; we don't handle the case of
`bootc update` followed by a `bootc update --apply`.

We need to compare booted/staged and dispatch on that.

**Comment by jeckersb** [comment]
I'd like to take a stab at this tomorrow

**Comment by jeckersb** [comment]
I'd still like to do this, but on my first foray I ran face-first into my own ignorance of the technical details of ostree.  So I've been trying to crash course that to get up to speed.  I'll be out starting tomorrow until after the holiday, so if someone else is motivated to take this and run with it, by all means have at it.  Otherwise I'll resume this in January.
