### ISSUE TITLE
bootc install to-disk --disable-selinux does not disable selinux when the host has selinux disabled

### ISSUE THREAD

**Issue by ckyrouac** [containers/bootc#303]
The purpose of the `--disable-selinux` command is to enable the creation of an image with selinux enabled from a host with selinux disabled. On my Fedora 39 machine, when I set selinux to disabled or permissive, [this selinux_enabled check](https://github.com/containers/bootc/blob/8969314f224754b6bb282afc21a3235c08298bb4/lib/src/lsm.rs#L27) still returns true. This results in an image with broken selinux that won't fully boot. Would checking the output of getenforce be more reliable?

**Comment by cgwalters** [comment]
Yeah, that check is wrong - it only works on Ubuntu where it's load bearing because they don't compile in support at all.

OK so...this problem heavily overlaps with that of https://github.com/containers/bootc/pull/302 

Basically what we want to change here is replacing parsing `/proc/filesystems` with checking for `/proc/1/root/sys/fs/selinux`.

That change alone is probably sufficient.

**Comment by ckyrouac** [comment]
@bcrochet are you already working on this? If not I'd like to take a stab at it.

**Comment by bcrochet** [comment]
> @bcrochet are you already working on this? If not I'd like to take a stab at it.

Sort of? I actually started on a different section of the code that will ensure that the selinuxfs is mounted inside the container. If you want to focus on the selinux_enabled check and getting that working properly, I'd appreciate that.

Feel free to assign yourself to this issue as it's not directly tied to what I'm working on.
