### ISSUE TITLE
Requires `-v /dev:/dev` for reliable loopback

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#352]
Sometimes I see:

```
DEBUG exec: "losetup" "--show" "-P" "--find" "/output/bootc.raw"
losetup: /output/bootc.raw: failed to set up loop device: No such file or directory
```

I think we may need to wait on udev on the host.

**Comment by cgwalters** [comment]
This isn't a race at all, it's simply that by default that docker from the very start has created a static snapshot of `/dev` as a `tmpfs` and this behavior was copied into podman.  So the first time we run, we won't see the loop device we created.  But when it's created, the next run we will.  There's a bunch of issues around this and generally it's suggested to just `-v /dev:/dev`.  I'm tempted to do that...but it's yet another thing in our install invocations...so it'd be nicer to do a dynamic remount.

**Comment by mvo5** [comment]
Indeed, we ran into a similar issue in bib - we did https://github.com/osbuild/osbuild/pull/1468 to fix it, i.e. if we know what loop device we need and it's not available in the container we just create the device node.

**Comment by ericcurtin** [comment]
For the record, I do think something in podman and/or osbuild changed recently that this is now required.

Have been building images using a similar technique with loopback mounts, all of a sudden `-v /dev:dev` is needed:

https://gitlab.com/CentOS/automotive/sample-images/-/merge_requests/481

Note ublue hit something similar recently also (all within weeks of each other and we likely all consume osbuild/podman changes at slight different times because of differences in versioning techniques):

https://github.com/ublue-os/isogenerator/issues/22

The lorax pointed out showed a possible alternate technique that could be use in containers also, the osbuild scripts could do something like this maybe:

```
if (we_are_a_container)
{
  mknod
  losetup
}
```

https://github.com/rhinstaller/anaconda/blob/master/dockerfile/anaconda-iso-creator/lorax-build#L27

but maybe this is bikeshed since -v /dev:/dev works
