### ISSUE TITLE
Add mdbook-linkcheck to CI

### ISSUE THREAD

**Issue by jeckersb** [containers/bootc#521]
https://github.com/Michael-F-Bryan/mdbook-linkcheck

I've been catching these manually[1], but unsurprisingly computers are better at parsing things than my fallible biological parser.

[1] https://github.com/containers/bootc/pull/520/files/615ead5c9cc85066ef07af1da5321d1c112acc4f#diff-e0b4a488eccbd4e71db5387b0916834520b83da8da89b17f1842760ffd5e1963

**Comment by cgwalters** [comment]
OK I had to revert this as it broke the site.  I only dug in a bit but I *think* the problem is that the `linkcheck` run seems to add a new top-level `linkcheck/` directory in the output paralleling the `html/` directory from the main run.

We could probably just remove it.  Or, maybe we don't need to run link check on the main build?

Needs some investigation and testing.

**Comment by jeckersb** [comment]
> OK I had to revert this as it broke the site. I only dug in a bit but I _think_ the problem is that the `linkcheck` run seems to add a new top-level `linkcheck/` directory in the output paralleling the `html/` directory from the main run.
> 
> We could probably just remove it. Or, maybe we don't need to run link check on the main build?
> 
> Needs some investigation and testing.

Of course I just read this after I wrote https://github.com/containers/bootc/pull/533#issuecomment-2112971710#533

So yes, that's the problem.  We might as well run linkcheck again on the main build, but we just need to upload the artifacts correctly with the right path.
